### PR TITLE
regenerate gomocks

### LINKED ISSUE #750: tests failing because of gomock
Seems to be related to a recent update of gomock:

```
# github.com/lucas-clemente/quic-go/internal/mocks
internal/mocks/cpm.go:42: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:52: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:62: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:72: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:82: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:92: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:102: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:112: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:122: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:132: not enough arguments in call to _mr.mock.ctrl.RecordCall
	have (*MockConnectionParametersManager, string)
	want (interface {}, string, reflect.Type, ...interface {})
internal/mocks/cpm.go:132: too many errors
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #750.

I also added a README, because I keep forgetting the command to regenerate this stuff.

### CODE REVIEW

**Comment by lucas-clemente** [comment]
LGTM, but please check why the integration tests are failing.

**Comment by marten-seemann** [comment]
I reran the tests and (due to some new changes in gomock introduced in https://github.com/golang/mock/commit/dea6b4faed39e3cf900ad31554956a60f71a4d17) they're all failing now, rerunning `go generate` does not help.

@lucas-clemente: Can you please have a look asap? gomock is now effectively blocking all progress on quic-go.

**Comment by lucas-clemente** [comment]
This looks fixed on the gomock side: https://travis-ci.org/lucas-clemente/quic-go/builds/256785728 (current master). Closing this PR.

**Comment by marten-seemann** [comment]
No, it is not fixed. Please run `go generate` and then run the tests. They all fail.

**Comment by marten-seemann** [comment]
Works now. Whatever. Closing this.
